
#include "stdtypes.h"
#include "stdio.h"
#include "x86.h"
#include "disk.h"
#include "ext.h"
#include "utility.h"
#include "memdefs.h"
#include "string.h"
#include "mbr.h"
#include "alloc.h"

typedef void (*KernelStart)();

void testContentsLargeFileExt();
void testSubdirectoryFileExt();
void loadAndJumpToKernelExt();
void printFileExt(Handle fin);
Bool validateFileExt(Handle fin);

Partition partitionTable[4];

void __attribute__((cdecl)) start(Uint16 bootDrive, void* pt)
{
    Bool ok;
    clearScreen();
    printf("Hello from Stage2. Boot drive = %x\n", bootDrive);

    heapInit(HEAP_ADDRESS, HEAP_SIZE);
    printHeap();

   // Copy partition table into a safe, known location
    Partition* pp = (Partition*)pt;
    for (int ii = 0; ii < 4; ++ii) {
        partitionTable[ii] = *(Partition*) pt;
        pt += sizeof(Partition);
    }
    printPartitionTable(partitionTable);

    ok = extInitialize(bootDrive, partitionTable);

    testContentsLargeFileExt();
    //testSubdirectoryFileExt();

    panic("Stop in main");
}

void testContentsLargeFileExt()
{
    Handle fin = extOpen("/8MB");
    if (fin == BAD_HANDLE) {
        panic("extOpen returned error");
    }
    printf("extOpen: fin = %u\n", fin);

    if (validateFileExt(fin)) {
        printf("SUCCESS!!\n");
    }

    extClose(fin);
}

void testSubdirectoryFileExt()
{
    const int BUFF_SIZE = 1024;
    char buff[BUFF_SIZE + 1];

    Handle fin = extOpen("/mydir/test2.txt");
    if (fin == BAD_HANDLE) {
        panic("extOpen returned error");
    }
    printf("extOpen: fin = %u\n", fin);

    if (extRead(fin, 10, buff) != 10) {
        printf("Couldn't read 10 characters :(\n");
    }

    if (memcmp(buff, "1234567890", 10) != 0) {
        printf("File contents not as expected\n");
    } else {
        printf("SUCCESS!!\n");
    }

    extClose(fin);   
}

void loadAndJumpToKernelExt()
{
    Handle fin = extOpen("/kernel.bin");
    if (fin == BAD_HANDLE) {
        panic("Failed to open kernel");
    }

    Uint8* kp = KERNEL_LOAD_ADDR;
    Uint32 count;
    while ((count = extRead(fin, SCRATCH_MEM_SIZE, SCRATCH_MEM_ADDRESS)) > 0) {
        printf("Copying %x bytes from %p to %p\n", count, SCRATCH_MEM_ADDRESS, kp);
        memcpy(kp, SCRATCH_MEM_ADDRESS, count);
        kp += count;
    }

    extClose(fin);

    Uint8* pp = KERNEL_LOAD_ADDR;
    for (int ii = 0; ii < 16; ++ii) {
        printf("%x ", pp[ii]);
    }
    printf("\n");

    KernelStart kernelStart = (KernelStart) KERNEL_LOAD_ADDR;
    printf("Jumping to kernel at %p\n", kernelStart);
    kernelStart();
}

/*
 * Print the contents of the file
 */
void printFileExt(Handle fin)
{
    const int BUFF_SIZE = 1024;
    char buff[BUFF_SIZE + 1];

    printf("File contents:\n");
    Uint32 count;
    while ((count = extRead(fin, BUFF_SIZE, buff))) {
        buff[count] = '\0';
        printf("%s", buff);
    }
}

/*
 * Check that the contents of the file matches what is generated by
 *      perl -e 'print pack "L*", 0..0x1fffff' > root/8MB
 * which is the 32 bit numbers from 0 to 0x1fffff in binary format
 */
Bool validateFileExt(Handle fin)
{
    const int BUFF_SIZE = 191; // Use a very oddly sized buffer to cause deliberately poor alignment with blocks
    Uint32 buff[BUFF_SIZE];
    Uint32 index = 0;
    Uint32 countBytes;
    while ((countBytes = extRead(fin, BUFF_SIZE * sizeof(Uint32), buff)) > 0) {
        Uint32 countInts = countBytes / sizeof(Uint32);
        for (int ii = 0; ii < countInts; ++ii) {
            if (buff[ii] != index + ii) {
                printf("File mismatch: index = %d (%#x), ii = %d (%#x), buff = %x\n", index, index, ii, ii, buff[ii]);
                return false;
            }
        }
        index += countInts;
    }
    printf("Validated %d (%#x) integers\n", index, index);
    return true;
}
